"""Initial schema

Revision ID: 97a755bb4189
Revises: 
Create Date: 2025-05-07 00:05:01.395192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97a755bb4189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_replies_id', table_name='replies')
    op.drop_index('ix_replies_original_comment_id', table_name='replies')
    op.drop_index('ix_replies_user_id', table_name='replies')
    op.drop_table('replies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_replies_user_id', 'replies', ['user_id'], unique=False)
    op.create_index('ix_replies_original_comment_id', 'replies', ['original_comment_id'], unique=False)
    op.create_index('ix_replies_id', 'replies', ['id'], unique=False)
    # ### end Alembic commands ###
